### ISSUE TITLE
dnsmasq containers going down

### ISSUE THREAD

**Issue by yasir2000** [samrocketman/docker-compose-ha-consul-vault-ui#10] opened 2021-07-19 17:22 UTC
Just as dnsmasq are trying to up, they both go down and nginx too. dnsmasq log is below, 

```
+ checksum -c /tmp/consul-template_0.26.0_linux_amd64.zip.sha256sum
+ type sha256sum
+ sha256sum -c /tmp/consul-template_0.26.0_linux_amd64.zip.sha256sum
sha256sum is /usr/bin/sha256sum
consul-template_0.26.0_linux_amd64.zip: OK
+ unzip consul-template_0.26.0_linux_amd64.zip
Archive:  consul-template_0.26.0_linux_amd64.zip
unzip: 'consul-template' exists but is not a regular file
```

The problem is with consul-agent,sh script function:

```
download() {
  # $1 is the application
  # $2 is the version
  # $3 may not exist but if so is the destination path
  if [ ! "$3" = "./" ] && type "$1" || [ -f "$1" ]; then
    return
  fi
  (
    zip_file="$1"_"$2"_linux_amd64.zip
    if [ -z "$3" ]; then
      cd "$bin_path"
    else
      cd "$3"
    fi
    curl -fL https://releases.hashicorp.com/"$1"/"$2"/"$1"_"$2"_SHA256SUMS | \
      grep -- "$zip_file" > /tmp/"$zip_file".sha256sum
    until checksum -c /tmp/"$zip_file".sha256sum; do
      curl -LO https://releases.hashicorp.com/"$1"/"$2"/"$zip_file"
      sleep 3
    done
    unzip "$zip_file"
    chmod 755 "$1"
    rm "$zip_file"
    rm /tmp/"$zip_file".sha256sum
  )
}


```
Because it does not download the zipped version right file:

https://releases.hashicorp.com/consul-template/0.26.0/

I have set enough permissions on all folders : `chmod -R 777` yet that didnt solve

**Comment by samrocketman** [comment] 2021-08-01 12:08
Hi @yasir2000, I can try to reproduce.  What is your OS?  What is the exact commands you typed to get the error?

**Comment by dualizeo** [comment] 2022-10-16 01:37
I am also having this issue :(

**Comment by samrocketman** [comment] 2022-10-24 05:46
I can try to reproduce.

**Comment by samrocketman** [comment] 2022-10-24 05:47
Would be good if you could provide more information.  Are you using non X86 hardware or something?

**Comment by samrocketman** [comment] 2022-12-10 17:03
I am on Ubuntu and have successfully provisioned this several times across Ubuntu 18 and 20.

I am closing this again since I can't reproduce.

I recommend filing a new issue with new details on how to reproduce if this is still a problem.

Saying it's broken without how to reproduce makes it hard to fix assuming there is something to fix.

**Closed by samrocketman** 2022-12-10 17:03 UTC

**Comment by samrocketman** [comment] 2024-08-21 01:56
So ehow I locked this issue by mistake
